### ISSUE TITLE
[BUG] When export in CSV, the error "v.replaceAll is not a function" is raised

### ISSUE THREAD

**Issue by jeffpoulton** [Baboo7/strapi-plugin-import-export-entries#1]
**Describe the bug**
When I attempt to export a collection, I get one of several error messages depending on the collection and the options I select. 

**To Reproduce**
1. Go to a collection'
2. Click on Export
3. Select CSV as the export type
4. Leave both options unchecked
5. Click Fetch Data
6. See error

<img width="860" alt="image" src="https://user-images.githubusercontent.com/19457/171504609-255326e4-0290-41dd-b92b-1fb26b09ec9e.png">

<img width="989" alt="image" src="https://user-images.githubusercontent.com/19457/171504545-9faa5b2e-ae0b-4f5b-83cd-87fceea52635.png">

If I check `Export relations as ids`, I get a different error:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/19457/171504697-85953dc5-22d1-48ab-ab83-ecfd41dd406a.png">
<img width="993" alt="image" src="https://user-images.githubusercontent.com/19457/171504819-7071fd7d-0afd-4ec2-8668-0b81e7589449.png">

**Expected behavior**

**Screenshots**

**Additional context**
I am able to export the collection as JSON, as long as I leave the `Export relations as ids` unchecked.

**Comment by Baboo7** [comment]
Hey @jeffpoulton, thanks for the issue ! Can you share the schema of the model you're trying to export? Plus what database do you use?

**Comment by mitri-dvp** [comment]
I believe that's a node version issue, it happened to me as well using node v14.19.0

in the file `server/services/data-converter/utils.js`, line 8 replace all method can be replaced with: `v.replace(/"/g, '""'))`

**Comment by Baboo7** [comment]
Fixed with [PR #3](https://github.com/Baboo7/strapi-plugin-import-export-entries/pull/3)
Version `1.3.2` is published
