### ISSUE TITLE
[FEATURE] Explain documentation

### ISSUE THREAD

**Issue by Charlesdoiron** [Baboo7/strapi-plugin-import-export-entries#10]
**Is your feature request related to a problem? Please describe.**
After installing the plugin, the documentation could be more detailed.

**Describe the solution you'd like**
1/ I need to know where to import `importData` from.
If I follow the doc - I get an error that tells me `ReferenceError: importData is not defined`.

2/ Have a confirmation that the script from the doc should be in `api/myContentType/services`

Thanks a lot for your work !

**Comment by Baboo7** [comment]
The method is exposed in the `import` service:

```
const service = strapi.plugin("import-export-entries").service("import");
await service.importData(/** */);
```

**Comment by Charlesdoiron** [comment]
Ok thanks a lot !
It's working : )

Another question :

Is it possible to check if an entity exist, if yes update-it if no create-it (without using the strapi id) ?

**Comment by Charlesdoiron** [comment]
Thanks !
