### ISSUE TITLE
[BUG] Large collections do not export

### ISSUE THREAD

**Issue by danielgaming412** [Baboo7/strapi-plugin-import-export-entries#106]
I am experiencing an issue when attempting to export a large collection of over 270k entries using the Strapi Import Export plugin.

- The issue occurs when trying to export the collection from the page itself and when exporting the entire database.
- The exported collection appears, but it is empty (no entries).
- The issue is only happening with this large collection, smaller collections are exporting as expected.

**Additional information:**

strapi: 4.8.2
strapi-plugin-import-export-entries: 1.18.0

Is there any additional information needed ?
What would be the workaround here ? 

Thank you. 

<img width="852" alt="Capture d’écran 2023-04-17 à 15 56 11" src="https://user-images.githubusercontent.com/97158420/232505759-2af5de97-dba7-48e2-be66-03f2dfc4a5f9.png">

**Comment by Baboo7** [comment]
@danielgaming412 can you give it a try with latest version?

**Comment by danielgaming412** [comment]
Hi @Baboo7, I just tried with the version 1.19.1… Unfortunately same thing. 

BUT ! 
By default, the deepness is set to 5, and changing it to 1 resolved it ! Actually, anything above 1 won't work with very large collection.

**Comment by Baboo7** [comment]
Sounds good. I'm marking this issue as solved and I'll add a disclaimer in the README
