### ISSUE TITLE
Plugin doesn't import items from navigation plugin

### ISSUE THREAD

**Issue by vjsampas** [Baboo7/strapi-plugin-import-export-entries#118]
Hi,

We have installed strapi navigation plugin in our environment & created big hierarchy for navigation. Now we want to migrate all content to another environment but seems that navigation hierarchy is not getting exported through import/export plugin.

"strapi-plugin-navigation": "^2.2.3"
"strapi-plugin-import-export-entries": "^1.18.0"
"@strapi/strapi": "4.7.0"

If it's not supported is there any alternative way to import this hierarchy?

**Comment by Baboo7** [comment]
I suspect it's linked to this issue https://github.com/Baboo7/strapi-plugin-import-export-entries/issues/99. I'll dig into that

**Comment by Baboo7** [comment]
@vjsampas checkout version `v1.19.2`, you will be able opt-in to export plugins content types when exporting the whole database

**Comment by vjsampas** [comment]
@Baboo7 Thank you for your reply. I tried with v1.19.2 but unfortunately it doesn't detect the Navigation plugin. But it does detect other plugin like seo & media library. Below is snippet of strapi admin

![image](https://github.com/Baboo7/strapi-plugin-import-export-entries/assets/128164448/a30b7519-600e-46a3-894f-edd001ff995a)

**Comment by vjsampas** [comment]
It works with v1.19.2. Thanks
