### ISSUE TITLE
[FEATURE] Update entity if existing

### ISSUE THREAD

**Issue by Charlesdoiron** [Baboo7/strapi-plugin-import-export-entries#12]
**Is your feature request related to a problem? Please describe.**
Hi !
I would like to check if an entity exists using a field other than its `strapi_id`.
If the entity exists, the import updates the entity otherwise it created it

Thanks !

**Comment by Baboo7** [comment]
Interesting feature. I just added it in the todo

**Comment by Baboo7** [comment]
Just published version `1.6.0`. You can now select the field used as an id when importing data (only for the entry, not its relations)
