### ISSUE TITLE
[BUG] Empty admin page with Strapi 4.10.5

### ISSUE THREAD

**Issue by murbanowicz** [Baboo7/strapi-plugin-import-export-entries#120]
**Describe the bug**
I have tried to install this plugin, but after many tries it is still not working.

**To Reproduce**
Strapi 4.10.5 with TypeScript.

1. Installed the package `"strapi-plugin-import-export-entries": "^1.19.2"`
2. Modified plugins.ts
3. Modified webpack config:
```'use strict';

const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

/* eslint-disable no-unused-vars */
module.exports = (config, webpack) => {
  config.plugins.push(new MonacoWebpackPlugin());

  return config;
};
```
4. Removed dist/build and .cache
5. Ran `pnpm run build` 
6. http://localhost:1337/admin -> `Uncaught TypeError: Cannot set properties of undefined (setting 'apex')`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Baboo7** [comment]
Can you try to remove the webpack config above completely and tell me if it works?

**Comment by Baboo7** [comment]
@murbanowicz have you tried removing the webpack config?

**Comment by Przecza** [comment]
@Baboo7 I have the same issue. When I remove webpack config, the administration works. 

Strapi: 4.10.8

**Comment by Baboo7** [comment]
All right 👍  I removed the webpack configuration from the installation section. I'm closing this issue now
