### ISSUE TITLE
[BUG] NotFound component not found in @strapi/helper-plugin

### ISSUE THREAD

**Issue by nicoXXXXXtitan** [Baboo7/strapi-plugin-import-export-entries#129]
**Describe the bug**
NotFound component not found in @strapi/helper-plugin

since some strapi maj, I have a warning in the console about the NotFound component that is not found.
![Error 4](https://github.com/Baboo7/strapi-plugin-import-export-entries/assets/50142206/c91835e8-5e78-444b-82a4-e0990726a61d)

On the Strapi project, a PR corrects the problem by replacing the NotFound component with component  AnErrorOccurred. This PR has been merged with version 4.9.1.
See the PR: https://github.com/strapi/strapi/pull/16335

**Comment by iamandrewluca** [comment]
The component `NotFound was replaced with `AnErrorOccurred`

I suppose they introduced a breaking change somewhere

https://github.com/strapi/strapi/pull/16335

**Comment by Baboo7** [comment]
@nicoXXXXXtitan issue should be fixed in `v1.21.1`

**Comment by nicoXXXXXtitan** [comment]
Great !! Thank you !
Have a nice day.
