### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by uranetz** [Baboo7/strapi-plugin-import-export-entries#137]
**Describe the bug**
Media content does not uploaded when import entries in format JSON v2

**To Reproduce**

1. Create collection, ex. "Products" with Media type property named "images" 
2. Go to Content Manager and choose collection Products
3. Click on Button Import and paste data in 
`{
	"version": 2,
	"data": {
		"api::product.product": 	{"1":{"id":1,"images":{"url":"PATH_TO_IMAGE_FROM_THE_WEB"}}}
			}
}`
4. Click Import Button
5. See Success message
6. View Product entry details with no image added

**Expected behavior**

View Product entry details with image uploaded from the web and added to entry with Id 1 as it's happened when import data in JSON v1 format:
`{"id":1,"images":{"PATH_TO_IMAGE_FROM_THE_WEB"}}`

**Additional context**
If we use short syntax for Media with JSON v2 format:
`{
	"version": 2,
	"data": {
		"api::product.product": {"1":{"id":1,"images":"PATH_TO_IMAGE_FROM_THE_WEB"}}
                    }
}`
Then after import we saw error result : 
`[
	{
		"error": {
			"name": "ValidationError",
			"message": "1 relation(s) of type plugin::upload.file associated with this entity do not exist",
			"details": {
				"errors": [
					{
						"path": [],
						"message": "1 relation(s) of type plugin::upload.file associated with this entity do not exist",
						"name": "ValidationError"
					}
				]
			},
			"level": "\u001b[31merror\u001b[39m",
			"timestamp": "2023-08-03 11:34:40.584"
		},
		"data": {
			"id": 1,
			"images": "PATH_TO_IMAGE_FROM_THE_WEB"
		}
	}
]`

**Comment by tcherokee** [comment]
I think this might be related to my [issue](https://github.com/Baboo7/strapi-plugin-import-export-entries/issues/148) . I also got this error while I was trying to import some entries. I then tried importing the media separately and noticed that some of the images don't upload properly. It seems like they sometimes use an incorrect id which causes a conflict and results in the image not uploading.

**Comment by Baboo7** [comment]
@uranetz imported data should match this structure to import media:

```json
{
  "version": 2,
  "data": {
    "api::product.product": {
      "1": {
        "id": 1,
        "images": 1 // refers to the id of plugin::upload.file
      }
    },
    "plugin::upload.file": {
      "1": {
        "url": MEDIA_URL
      }
    }
  }
}
```
