### ISSUE TITLE
[BUG] Adding `cdn.jsdelivr.net` to the CSP makes it ineffective

### ISSUE THREAD

**Issue by JWesorick** [Baboo7/strapi-plugin-import-export-entries#15]
**Describe the bug**

(As I understand it) Adding `cdn.jsdelivr.net` to the content security policy effectively makes the content security policy ineffective since any content can be hosted on cdn.jsdelivr.net.

**Comment by Baboo7** [comment]
I agree this is a security issue. It's a quick and dirty way until I find a way to load the monaco editor locally instead of from a cdn

**Comment by Baboo7** [comment]
@JWesorick see latest version `1.6.3` and the updated [installation doc](https://github.com/Baboo7/strapi-plugin-import-export-entries#installation) to fix the issue.
