### ISSUE TITLE
[BUG] Importing and exporting images fails because of different images ids

### ISSUE THREAD

**Issue by mohammed-sabra** [Baboo7/strapi-plugin-import-export-entries#152]
For importing/exporting media the strategy as is followoing

the media must have an id, hash, name or url property. First the media is searched by id, then by hash, then by name and finally imported from url if not found previously.

I want the search to be with url first not by id

How I can do it?

**Comment by Baboo7** [comment]
@mohammed-sabra checkout verson 1.22.1 where media import is much more stable
