### ISSUE TITLE
[FEATURE] Document JSON v2 export format in Services and Content API sections

### ISSUE THREAD

**Issue by mjarosie** [Baboo7/strapi-plugin-import-export-entries#155]
**Is your feature request related to a problem? Please describe.**
The export API takes `exportFormat` parameter that can take the value of `"json-v2"` which is an undocumented feature.

**Describe the solution you'd like**
That functionality should be described in the README in both Services and Content API sections.

**Comment by Baboo7** [comment]
@mjarosie good point. The doc is now mentioning the json v2 export format
