### ISSUE TITLE
[BUG] @strapi/design-system dependency

### ISSUE THREAD

**Issue by ShahriarKh** [Baboo7/strapi-plugin-import-export-entries#161]
After upgrading to the latest version, webpack complains about icons not being found (I updated some other plugins and also strapi itself, so I'm not really sure what caused the break)  
```js
ERROR in ./node_modules/strapi-plugin-import-export-entries/admin/src/pages/HomePage/HomePage.js 5:0-61
Module not found: Error: Can't resolve '@strapi/design-system/Layout' in 'AAA\node_modules\strapi-plugin-import-export-entries\admin\src\pages\HomePage'

ERROR in ./node_modules/strapi-plugin-import-export-entries/admin/src/pages/HomePage/HomePage.js 7:0-62
Module not found: Error: Can't resolve '@strapi/design-system/Select' in 'AAA\node_modules\strapi-plugin-import-export-entries\admin\src\pages\HomePage'

ERROR in ./node_modules/strapi-plugin-import-export-entries/admin/src/pages/HomePage/HomePage.js 8:0-62
Module not found: Error: Can't resolve '@strapi/design-system/Typography' in 'AAA\node_modules\strapi-plugin-import-export-entries\admin\src\pages\HomePage'
```
I tried uninstall/reinstalling the plugin, and also removing node_modules and pacakge-lock.json, but no luck.  
The only solution I found is to manually install `@strapi/design-system` as a dependency.

Is that a strapi bug, or adding design-system as a dependency of this plugin is the way to go?

strapi: v4.15.5
strapi-plugin-import-export-entries: v1.22.2
node: v18.17.0

**Comment by DanielPantle** [comment]
I got a similar problem with version 1.23.0. I get one of the following errors when either upgrading react-router-dom from 5.3.4 to 6.21.1 (tested it multiple times, unfortunatelly I don't remember when I got which error)

> Building admin panel[ERROR] Module not found: Error: Can't resolve '@strapi/design-system/Button' in '[...]/node_modules/strapi-plugin-import-export-entries/admin/src/components/ImportButton'

> Building admin panel[ERROR] Module not found: Error: Can't resolve '@strapi/design-system/Box' in '[...]/backend/node_modules/strapi-plugin-import-export-entries/admin/src/components/InjectedImportExportSingleType'

strapi: 4.16.2
strapi-plugin-import-export-entries: 1.23.0
node: 20.1

**Comment by Baboo7** [comment]
I updated the imports in version 1.23.1. It should be good now
