### ISSUE TITLE
[BUG] Nested components with image fields do not get exported

### ISSUE THREAD

**Issue by cthom-dev** [Baboo7/strapi-plugin-import-export-entries#17]
**Using**
"strapi-plugin-import-export-entries": "^1.6.3"
"@strapi/strapi": "4.1.12",

Firstly thanks for making this plugin it has been great.

One Issue I have found is when exporting a collection with nested components if the nested component has a image field, it doesn't get exported, all the other fields in the nested component get exported, just not the image field.

For instance when using the Strapi SEO plugin, you have available an Seo component. Within the Seo component there is a component called "metaSocial" which as an image field, this image field doesnt get exported, in either json or csv

See screenshot attached to see SEO component schema.

https://imgur.com/a/KHtXIyT

Thanks for any help

**Comment by cthom-dev** [comment]
I ended up creating my own import functionality, but it seems that issue is just the export isn't being populated deeply enough for components (could be the same for relations and dynamic zones). I used the EntityService API.

Also you might be interested to know the csvtojson package you use, allows for converting csv into nested json objects, which I also used for my import, so I was able to create csv with column headings for every field, component (havent tested with dynamic zones) and import that way, which I think is much cleaner for non devs to populate spreadsheets for imports.

There is also a jsontocsv package which could be useful for exporting, again into a nested "friendly" csv format. Im going to test this when I get some time.

**Comment by Baboo7** [comment]
The export only goes two levels deep and populates the relations of relations. What you need is a third level of deepness. I'm thinking of computing the deepness of a relation to properly export such nesting.

As for the package `csvtojson` this is really interesting. I'll dig into that

**Comment by cthom-dev** [comment]
> The export only goes two levels deep and populates the relations of relations. 

I really appreciate your work in this plugin, and how quickly you address issues, so much thanks. I would though put in the docs about this limitation though as it could catch a few people, until its fixed that is :grin:

**Comment by Baboo7** [comment]
@cthom-dev I published version `1.6.7` where the seo component is populated automatically

**Comment by Ary428** [comment]
> The export only goes two levels deep and populates the relations of relations. What you need is a third level of deepness. I'm thinking of computing the deepness of a relation to properly export such nesting.
> 
> As for the package `csvtojson` this is really interesting. I'll dig into that

Hi!

I'm just tried to export three levels of components.

![Screen Shot 2022-07-20 at 9 41 48](https://user-images.githubusercontent.com/72888630/179914643-898b0458-f3c5-4e4c-86ab-9c6d8d1370ff.png)

But in the exported JSON there's no nested component at all:(

![Screen Shot 2022-07-20 at 9 45 01](https://user-images.githubusercontent.com/72888630/179915029-dc4aa428-774e-4eae-9b57-26b49be76a1d.png)


Do you know when the problem will be solved?

**Comment by Benman2005** [comment]
@Baboo7 I actually have the same issue as @Ary428 working with nested components about 4 levels deep.. love the plugin, and if exporting/importing a little deeper is possible, this would greatly enhance its use for me :)
I'm on version 1.6.3 and upgrading to 1.6.7 or 8 or 9 only makes the fetching/populating less deep.. am i doing something wrong?

**Comment by Baboo7** [comment]
I need to figure out first how to prevent circular references to properly increase the deepness.
I wonder if a first step could be to let you decide the deepness of the export. Could it be an interesting feature to you?

**Comment by Santiago-j-s** [comment]
I have the same problem, being able to choose the nesting level of the export utility would be great!

**Comment by Baboo7** [comment]
Update: version `1.7.0` is out and export deepness is parametrized on server side. Deepness has been increased to 5 (previously 2)

This is an intermediary version until the deepness option becomes available in the UI

**Comment by Santiago-j-s** [comment]
Ty!
