### ISSUE TITLE
Apply search isn't working anymore since the latest strapi

### ISSUE THREAD

**Issue by kevinvugts** [Baboo7/strapi-plugin-import-export-entries#182]
**Describe the bug**
When click export on a collection types listview and apply some filters to it. The exported data isn't respecting the filters applied.

**To Reproduce**
1. Go to a collection type 
2. Filter on a single id
3. press export data
4. check "apply search and filters"
5. data returned is just the whole db..

**Expected behavior**
It should only return the data for the collection-type/slug that the filter applied for. 

**Screenshots**
Not applicable.

**Additional context**
Nope.

**Comment by kevinvugts** [comment]
My apologizes. This was caused by an internal issue in my decorators

**Comment by pgmaier** [comment]
@kevinvugts Could you expand on what the issue was? I am experiencing the same issue. Thanks.

**Comment by kevinvugts** [comment]
> @kevinvugts Could you expand on what the issue was? I am experiencing the same issue. Thanks.

I overwrote the default entityService of Strapi. And that was causing an issue in the population / filters /  field selection. And thus, not applying the search correctly.
