### ISSUE TITLE
[FEATURE] Support for media upload

### ISSUE THREAD

**Issue by matepaiva** [Baboo7/strapi-plugin-import-export-entries#19]
**Is your feature request related to a problem? Please describe.**
I need to be able to upload images related to other collection types, but I am not sure if it is possible or how to do it. If it's possible, it would be good to be documented. I could help with that.

**Comment by Baboo7** [comment]
Uploading media is still under development. I'll notify you when it will be working.

What do you mean by _upload images related to other collection types_?

**Comment by cthom-dev** [comment]
Media upload would be fantastic.

**Comment by Baboo7** [comment]
All right, I published version `1.6.4` that supports media upload.
I did few tests and it seems to work properly but I'm waiting for your feedback

**Comment by matepaiva** [comment]
@Baboo7 sorry, I couldn't understand how to use it to import the images. My use case is: I have a set of articles that have a featured image and, as I import the articles (from a json array), I want to be able to also import (upload) the featured image. Is that possible, for example?

**Comment by matepaiva** [comment]
How can I upload `featured_image` on import?

articles.json:
```json
[
  {
    "id": 5,
    "createdAt": "2010-03-10T17:07:44.000Z",
    "createdBy": 1,
    "updatedBy": 1,
    "publishedBy": 1,
    "publishedAt": "2010-03-10T17:07:44.000Z",
    "updatedAt": "2010-03-10T22:55:33.000Z",
    "title": "Primeiro \"bairro\" de Lisboa com representação em 3D",
    "slug": "primeiro-bairro-de-lisboa-com-representacao-em-3d",
    "excerpt": "",
    "content": "<p>De acordo com as pretensões do requerente e indo de encontro àquilo que entende ser as suas necessidades, propõe-se a edificação de um edifício composto por dois pisos, desenvolvendo-se em dois planos</p>",
    "featured_image": "https://www.anteprojectos.com.pt/wp-content/uploads/2010/03/35850b.jpg",
    "categories": [{ "id": 7 }, { "id": 8 }],
    "tags": [],
    "projects": [],
    "companies": []
  }
]
```

![image](https://user-images.githubusercontent.com/9984086/179050723-089dfd60-22c7-4dfc-820f-3e5bb930d9bd.png)

**Comment by Baboo7** [comment]
Based on your needs I published version `1.6.5`. You'll be able to import the media using a url as you expect for `featured_image`.

Check out the [Importing Data section of the doc](https://github.com/Baboo7/strapi-plugin-import-export-entries#importing-data).

**Comment by matepaiva** [comment]
@Baboo7 sorry for the delay in the feedback, I was envolved in other projects as well. Today I tried it and it works very well!

Giving you additional feedback, I missed some features. If you wish, I could open a new issue. 

Based on the current documentation, I sent the following `media` object:

```json
[
  {
    "title": "test",
    "media": {
      "id": 31896,
      "url": "http://www.anteprojectos.com.pt/wp-content/uploads/2010/03/35850a.jpg",
      "name": "blablabla.jpg"
    }
  }
]
```

My thoughts on that are:
- the `id` is not being respected. As I passed the `url`, it ignores the `id`, but it would be great to save that media with that `id`, although I am not sure that this is possible.
- The `name` is not being respected.
- it would be good to have the ability to set the `alternativeText` and `caption`.

## Current result to the import above:
![image](https://user-images.githubusercontent.com/9984086/183709233-e1f7dbec-85c3-4968-8883-97480a75e11f.png)

**Comment by Baboo7** [comment]
Great feedback 🙏

Can you open a Feature Issue with these suggestions?
