### ISSUE TITLE
[BUG] - Compatibility issue with CKEditor5 plugin

### ISSUE THREAD

**Issue by kevinvugts** [Baboo7/strapi-plugin-import-export-entries#193]
**Describe the bug**
When exporting and importing a collection type containing a CKEditor field. This plugin does not account for the media files updates in the value of this fields. And thus resulting in corrupt media upload files and referencing old values.

**To Reproduce**

1. Upload an image in a CKEditor field of Strapi.
2. Export the collection type
3. Import the collection type in another Strapi
4. Check the link not representing the correct url

**Expected behavior**
It should check if the file in the CKEditor needs to be uploaded first
Secondly it should update the field with the new url of the uploaded fiels
And it should import the new collection type

**Screenshots**
![image](https://github.com/Baboo7/strapi-plugin-import-export-entries/assets/17518874/bb768b6b-11f8-4857-a714-e55dfa34b021)

**Additional context**
Not applicable. This issue is clear.

Possible duplicate: #69

**Comment by kevinvugts** [comment]
> **Describe the bug** When exporting and importing a collection type containing a CKEditor field. This plugin does not account for the media files updates in the value of this fields. And thus resulting in corrupt media upload files and referencing old values.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Upload an image in a CKEditor field of Strapi.
> 2. Export the collection type
> 3. Import the collection type in another Strapi
> 4. Check the link not representing the correct url
> 
> **Expected behavior** It should check if the file in the CKEditor needs to be uploaded first Secondly it should update the field with the new url of the uploaded fiels And it should import the new collection type
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/17518874/328462854-bb768b6b-11f8-4857-a714-e55dfa34b021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzM2NTQsIm5iZiI6MTcxNTA3MzM1NCwicGF0aCI6Ii8xNzUxODg3NC8zMjg0NjI4NTQtYmI3NjhiNmItMTFmOC00ODU3LWE3MTQtZTU1ZGZhMzRiMDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA5MTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZmY2MmZhM2FmZDgxMWIwODExNDMwYmNiYTZiMDg1ZGViOWIzOTBlNjQwMGQzNmUxYTQ4MDZkMTA5OWQyMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uicEwPYky4boUjMj5wZgyl9Y1-kGh3CS3WP1PsAsFGc)
> 
> **Additional context** N

Possible duplicate
#69

**Comment by H-Gomez** [comment]
@kevinvugts Have you managed to find a solution for this? We are seeing the same issue.

**Comment by kevinvugts** [comment]
> @kevinvugts Have you managed to find a solution for this? We are seeing the same issue.

I can definitely give you some tips. But i am unable to provide you the full code sample. 
Here is some pseudo code that should get you going.

We leverage the lifecycle methods of Strapi to basically find and replace the referenced media urls inside the content string of CKEditor. The value of the CKEditor is saved as a string which you should parse.

After parsing you should do a few things:

- Parse the string to a DOM using JSDom for example
- Search for "<img>" tags and find and replace the files by importing them again

```
const { handleCkEditorContent } = require("../../utils/handleCkEditorContent");

module.exports = {
  async beforeUpdate(event) {
    const ctx = strapi.requestContext.get();
    const { user } = ctx.state;
    const { model } = event;
    const { data } = event.params;

    // find all attributes with customField plugin::ckeditor5.CKEditor and handle the content
    const ckEditorAttributes = Object.entries(model.attributes).filter(
      ([key, value]) => value.customField === "plugin::ckeditor5.CKEditor"
    );

    for (const [key, value] of ckEditorAttributes) {
      if (data[key]) {
        data[key] = await handleCkEditorContent(data[key], user);
      }
    }
  },
  async beforeCreate(event) {
    const ctx = strapi.requestContext.get();
    const { user } = ctx.state;
    const { model } = event;
    const { data } = event.params;

    // find all attributes with customField plugin::ckeditor5.CKEditor and handle the content
    const ckEditorAttributes = Object.entries(model.attributes).filter(
      ([key, value]) => value.customField === "plugin::ckeditor5.CKEditor"
    );

    for (const [key, value] of ckEditorAttributes) {
      if (data[key]) {
        data[key] = await handleCkEditorContent(data[key], user);
      }
    }
  },
};
```

**Comment by H-Gomez** [comment]
Thank you, very helpful!
