### ISSUE TITLE
[QUESTION] Import trigger webhook?

### ISSUE THREAD

**Issue by DatCanCode** [Baboo7/strapi-plugin-import-export-entries#20]
Does your plugin trigger webhook when I import data from file? I can't find it in your document.

**Comment by Baboo7** [comment]
Atm webhook is triggered only for media, not for other data

**Comment by Baboo7** [comment]
I added a [section about webhook in the doc](https://github.com/Baboo7/strapi-plugin-import-export-entries#webhook). Closing this issue
