### ISSUE TITLE
[BUG]  Payload too large

### ISSUE THREAD

**Issue by jonadeline** [Baboo7/strapi-plugin-import-export-entries#21]
Hi there,
First, thanks for this promising plugin :) 

I'm experimenting an issue when i try to import a JSON or CSV,  the browser is raising a 413 HTTP error (payload too large).
Is there a way to increase the limit ?

**Comment by Baboo7** [comment]
The limitation comes from the middleware `body` from Strapi. Here is how to raise the limit:

```js
// ./config/middlewares.js

module.exports = {
  // ...
  {
    name: 'strapi::body',
    config: {
      jsonLimit: '10mb',
    },
  },
  // ...
}
```

See the [middleware doc](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/middlewares.html#internal-middlewares-configuration-reference)

**Comment by Baboo7** [comment]
I updated the [config section of the doc](https://github.com/Baboo7/strapi-plugin-import-export-entries#config)

**Comment by jonadeline** [comment]
Merci :)

**Comment by molul** [comment]
Hi. I just had the same error message, and I've opened my config/middlewares.js file, but I see an array of strings, not a json object. This is the content:

```
module.exports = [
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```

How should I add the code @Baboo7 mentions above?

```
module.exports = {
  // ...
  {
    name: 'strapi::body',
    config: {
      jsonLimit: '10mb',
    },
  },
  // ...
}
```

**Comment by Baboo7** [comment]
@molul you have to replace the string with the object, like this:

```js
module.exports = [
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  {
    name: 'strapi::body',
    config: {
      jsonLimit: '10mb',
    },
  },
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```

**Comment by molul** [comment]
Worked like a charm. Thanks!
