### ISSUE TITLE
[BUG] Importing Images while using AWS S3 strips extention and folder

### ISSUE THREAD

**Issue by kenshobotuser** [Baboo7/strapi-plugin-import-export-entries#26]
**Describe the bug**
I am uploading an entry into a collection which has an image. The image uploads but I then get a white screen on the collection page. Looking at the database, I can see the URL got imported, but the aws folder and the image extension both seemed to have been stripped out. If I upload the image using the media upload button it works properly.

![Screenshot 2022-07-28 at 20 06 23](https://user-images.githubusercontent.com/109878711/181617839-bf795193-8268-4d23-9ed6-21ab47f231e1.png)

In the screenshot above, the first entry was uploaded normally, but the second and third were imported and they are missing both the image extension and the image folder. The second image should be `https://giochigatsby.s3.eu-west-1.amazonaws.com/misc_images/chrismitoli_2021-10-26-170225_icpo.jpeg` instead of `https://giochigatsby.s3.eu-west-1.amazonaws.com/chrismitoli_2021-10-26-170225_icpoundefined`.

This is the import JSON I am currently using

```
[
            {
                "id": "23",
                "username": "christopher",
                "firstName": "Christopher",
                "lastName": "Mitoli",
                "photo": "https://giochigatsby.s3.eu-west-1.amazonaws.com/misc_images/chrismitoli_2021-10-26-170225_icpo.jpeg",
                "metaTitle": "Christopher",
                "metaDescription": null
            }
]
```

**Additional context**
I am using the [AWS-S3 provider ](https://market.strapi.io/providers/@strapi-provider-upload-aws-s3)plugin

**Comment by kenshobotuser** [comment]
just realised I was still signed into the wrong account :(.

**Comment by Baboo7** [comment]
If there is no issue I close this one ;)

**Comment by kenshobotuser** [comment]
Hi, there is still a issue with this unfortunately :(.

**Comment by Baboo7** [comment]
What the issue then?

**Comment by kenshobotuser** [comment]
So, using the JSON below, I am trying to import a image into a media field using a URL

```
[
            {
                "id": "23",
                "username": "christopher",
                "firstName": "Christopher",
                "lastName": "Mitoli",
                "photo": "https://giochigatsby.s3.eu-west-1.amazonaws.com/misc_images/chrismitoli_2021-10-26-170225_icpo.jpeg",
                "metaTitle": "Christopher",
                "metaDescription": null
            }
]
```

Right after the import I get a white screen and when I check the files table in the database, the URL for the image was imported but with the image folder missing and the image extension shown as undefined. So this is what end up being saved in the db

```
https://giochigatsby.s3.eu-west-1.amazonaws.com/chrismitoli_2021-10-26-170225_icpoundefined
```
Which is what is causing the white screen. If I add the correct image extension and folder to the URL, everything works as expected. Also, if I upload the image to the media field directly, it uses the correct URL.

I am using the AWS S3 provider plugin for saving images to S3, I do not know if that might have any bearing on the issue

**Comment by Baboo7** [comment]
> just realised I was still signed into the wrong account :(.

To better understand, what did you mean?

**Comment by kenshobotuser** [comment]
Ah, the github account i wrote the issue with is a bot account not my personal account. I forgot to log out of it after setting up some pipelines.

**Comment by kenshobotuser** [comment]
So I noticed the issue is still closed, does that mean it doesn't come from the plugin?

**Comment by Baboo7** [comment]
I will try to reproduce the issue using your image url

**Comment by keegankb93** [comment]
I can confirm that this happens when using AWS. Can't confirm with other providers.

**Comment by kenshobotuser** [comment]
Whew, I'm glad it wasn't me mucking things up :). My circumstance is that I am migrating my content from a different CMS to Strapi. So I have all the content exported in JSON format and I just needed to import them into Strapi. Your plugin is working perfectly for that barring the image issue.

**Comment by ohayak** [comment]
I confirm the same behavior with AWS s3

**Comment by Alex01d** [comment]
And that makes strapi pages with those images die.
Also the plugin creates database records of images even if their URLs return 404.

So we definitely need extra checks.

**Comment by Baboo7** [comment]
Seeing the impact of the issue this will be priority

**Comment by kenshobotuser** [comment]
Many thanks 🙏

**Comment by Baboo7** [comment]
Version `1.9.2` is available. Media import has been reworked for a more robust and consistent behavior:
- media import to AWS and other provider should work as expected
- import fails if the provided media url returns a status code ≠ `2xx`
- media import fully relies on strapi implementation now
- expected [data structure for media](https://github.com/Baboo7/strapi-plugin-import-export-entries#data-structure) has been updated in the doc (no breaking changes introduced)

**Comment by kenshobotuser** [comment]
Works like a charm. Many thanks for the quick fix 🙏

**Comment by ohayak** [comment]
version 1.9.2 is working as expected, but in 1.10 files are not uploaded to db nor the bucket

**Comment by Baboo7** [comment]
Give a try to version `1.10.1`, a fix has been pushed thanks to @Alex01d
