### ISSUE TITLE
[FEATURE] Import media with metadata (like id and caption)

### ISSUE THREAD

**Issue by matepaiva** [Baboo7/strapi-plugin-import-export-entries#32]
**Is your feature request related to a problem? Please describe.**
I need to import my multimedia files from an old system to strapi. Today it's possible to import it, but you can't mantain the ID reference, neither the caption, name or alternative text.

**Describe the solution you'd like**
Today if I import the following `media` object:
```
[
  {
    "title": "test",
    "media": {
      "id": 31896,
      "url": "http://www.anteprojectos.com.pt/wp-content/uploads/2010/03/35850a.jpg",
      "name": "blablabla.jpg"
    }
  }
]
```
- the id is not being respected. As I passed the url, it ignores the id, but it would be great to save that media with that id, although I am not sure that this is possible.
- The name is not being respected.
- it would be good to have the ability to set the alternativeText and caption.
- Also, it's only possible to import media if it is related with other content. I wish I could import media directly to `upload` or `file` content-type.
- 
**Describe alternatives you've considered**
I tried to import the files directly to the `File` content-type (via dashboard, importing to content-type `File` that is created by the core plugin "Upload"), but it does not work. It creates the register, but it does not upload the file.

**Comment by Alex01d** [comment]
As I can see from Strapi Plugin Upload, we can use 'hash' file property to determine original file locations: https://github.com/strapi/strapi/blob/master/packages/core/upload/server/services/upload.js#L85
So we can use any names, captions and alts.

**Comment by Alex01d** [comment]
Well, file hash is a slugified pathname without extension + some random string. Slugify function removes some characters from the pathname, e.g. underscore. So '/abc/__.jpg' and '/abc/_____.jpg' both become just 'abc'. That makes impossible to use 'hash' as a real pathname hash :(
Anyway here is my working example with name, alt, caption and search by hash: https://github.com/Alex01d/strapi-plugin-import-export-entries/tree/search-by-hash . I won't create PR from this branch, BTW I decided not to use filenames from Strapi in my frontends, filenames here are system things.

Also a version with alts and captions is on the way.

**Comment by SalahAdDin** [comment]
> **Is your feature request related to a problem? Please describe.** I need to import my multimedia files from an old system to strapi. Today it's possible to import it, but you can't maintain the ID reference, nor the caption, name, or alternative text.
> 
> **Describe the solution you'd like** Today if I import the following `media` object:
> 
> ```
> [
>   {
>     "title": "test",
>     "media": {
>       "id": 31896,
>       "url": "http://www.anteprojectos.com.pt/wp-content/uploads/2010/03/35850a.jpg",
>       "name": "blablabla.jpg"
>     }
>   }
> ]
> ```
> 
>     * the id is not being respected. As I passed the url, it ignores the id, but it would be great to save that media with that id, although I am not sure that this is possible.
> 
>     * The name is not being respected.
> 
>     * it would be good to have the ability to set the alternative text and caption.
> 
>     * Also, it's only possible to import media if it is related to other content. I wish I could import media directly to `upload` or `file` content-type.
> 
> 
> **Describe alternatives you've considered** I tried to import the files directly to the `File` content-type (via the dashboard, importing to content-type `File` that is created by the core plugin "Upload"), but it does not work. It creates the register, but it does not upload the file.

For us, right now, the most important thing should be importing media from the view directly instead to do it from content, later, we could just connect them in the admin.

But your idea is pretty good.

**Comment by Baboo7** [comment]
@Alex01d Thanks I'll have a look

**Comment by Baboo7** [comment]
> For us, right now, the most important thing should be importing media from the view directly

@SalahAdDin you mean an import interface like the one developped by Strapi?

**Comment by SalahAdDin** [comment]
> > For us, right now, the most important thing should be importing media from the view directly
> 
> @SalahAdDin you mean an import interface like the one developed by Strapi?

No no, the import/export button also in the Media view.

**Comment by Baboo7** [comment]
I published version `1.11.0`, the [doc is up-to-date on how to import media](https://github.com/Baboo7/strapi-plugin-import-export-entries#media). It's now possible to specify a file name, caption and alternative text when importing by url

**Comment by Baboo7** [comment]
@SalahAdDin in what would it be better than using the Strapi interface?

**Comment by SalahAdDin** [comment]
Well, we updated the plugin and we still don't see the import/export button directly in the Media view:
<img width="1464" alt="Screen Shot 2022-08-15 at 22 31 38" src="https://user-images.githubusercontent.com/5034215/184704248-21314a87-b337-4a7c-8e61-6c758673fbd1.png">

**Comment by Baboo7** [comment]
@SalahAdDin this page is about an issue different from the one you mention. Please, open a new issue for your use case

**Comment by SalahAdDin** [comment]
> @SalahAdDin this page is about an issue different from the one you mention. Please, open a new issue for your use case

Actually, it is the last point on the issues' requesting list, that's why I pointed it here.

**Comment by Baboo7** [comment]
@SalahAdDin in what would it be better than using the Strapi interface?

**Comment by SalahAdDin** [comment]
> @SalahAdDin in what would it be better than using the Strapi interface?

Sorry, I don't understand your question.

> Also, it's only possible to import media if it is related to other content. I wish I could import media directly to upload or file content-type.

It would be great to have the import/export button on the Media Content screen, you know when you can update all media and later you can fix the relations by yourself in the case you want.

**Comment by Baboo7** [comment]
Strapi developed a media library interface where you can upload several media at once (see the screenshot above you posted). Why do you need to have an export/import button on this interface?

**Comment by matepaiva** [comment]
> @SalahAdDin Strapi developed a media library interface where you can upload several media at once (see the screenshot above you posted). Why do you need to have an export/import button on this interface?

First of all, thank you again, you are a rock star for all the attention and patience you are having with us.

@Baboo7 I don't need to have the import button on that interface, but I need the ability to import it programmatically. Is there a way to programmatically import media not related to other content-types, specially setting the ID?

like:
```js
await service.importData(
  dataRaw: [{
    "id": 31896,
    "url": "http://www.anteprojectos.com.pt/wp-content/uploads/2010/03/35850a.jpg",
    "name": "blablabla.jpg"
  }],
  options: {
    slug: 'media', // <---- THIS?
    format: 'json'
  }
);
```

**Comment by matepaiva** [comment]
@Baboo7 does the name of the image must be unique? I imported two different

**Comment by Baboo7** [comment]
> First of all, thank you again, you are a rock star for all the attention and patience you are having with us.

Thanks for the feedback 😌 I'm doing my best to address fast all the relevant raised issues

## New version out

Version `1.13.0` is published. What's new:
- media `id` can be set! 🎉
- media can be imported programmatically:

```js
await service.importData(
  [
    {
      "id": 31896,
      "url": "http://www.anteprojectos.com.pt/wp-content/uploads/2010/03/35850a.jpg",
      "name": "blablabla.jpg"
    }
  ],
  options: {
    slug: 'media',
    format: 'jso', // <-- javascript object, not 'json'
  }
);
```

See full documentaion in the [services section](https://github.com/Baboo7/strapi-plugin-import-export-entries#services) and the [importing data section](https://github.com/Baboo7/strapi-plugin-import-export-entries#services) of the doc.

@SalahAdDin I digged into the strapi upload plugin and they don't provide injection zones on the media library page. This means I can't display an import/export button as done on the content type pages.

**Comment by SalahAdDin** [comment]
> > First of all, thank you again, you are a rock star for all the attention and patience you are having with us.
> 
> Thanks for the feedback 😌 I'm doing my best to address fast all the relevant raised issues
> ## New version out
> 
> Version `1.13.0` is published. What's new:
> 
>     * media `id` can be set! 🎉
> 
>     * media can be imported programmatically:
> 
> 
> ```js
> await service.importData(
>   [
>     {
>       "id": 31896,
>       "url": "http://www.anteprojectos.com.pt/wp-content/uploads/2010/03/35850a.jpg",
>       "name": "blablabla.jpg"
>     }
>   ],
>   options: {
>     slug: 'media',
>     format: 'jso', // <-- javascript object, not 'json'
>   }
> );
> ```
> 
> See full documentation in the [services section](https://github.com/Baboo7/strapi-plugin-import-export-entries#services) and the [importing data section](https://github.com/Baboo7/strapi-plugin-import-export-entries#services) of the doc.
> 
> @SalahAdDin I dug into the strapi upload plugin and they don't provide injection zones on the media library page. This means I can't display an import/export button as done on the content type pages.

Ok, no problem, we could suggest this on the forum.

**Comment by matepaiva** [comment]
I am closing this issue as every feature requested here was created. Thanks again @Baboo7!

**Comment by SalahAdDin** [comment]
I opened a feature request [here](https://feedback.strapi.io/feature-requests/p/injection-zones-on-the-media-library-page). 

Should I open it also in forums?

@matepaiva Thank you.

**Comment by Baboo7** [comment]
You can try
