### ISSUE TITLE
duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by everythinginjs** [Baboo7/strapi-plugin-import-export-entries#37]
**Describe the bug**
The error message came around after 216 imports and after that no single record can be added. the bellow image shows the error that I get. I am using a dynamic zone in my product page. when I try to add a record without dynamic zone it works fine but with that I get the bellow error.
![26ba7266-4b02-4276-b11b-572c2b124bf8](https://user-images.githubusercontent.com/34276557/184539593-ca26838a-bca6-4584-8ec3-df693057b4e4.jpeg)

**To Reproduce**
there is an issue on that in Strapi repo [link to that issue](https://github.com/strapi/strapi/issues/12493)

1. after importing 216 products with id relations I get the error.
2. Although I can edit those 216 products with no problem but the new record with return the mentioned error.
3. I just attached the csv to see what is it included.
4. I changed the dynamic zone to just repeatable components the issue still stays
**Expected behavior**
It should import 216 products with id relations and allow us to add new record for products table but it does not.
NOTE: I can add a new record without Dynamic Zone successfully.

**Screenshots**
I just attached files.

** my environment **
Strapi version: v4.1.9
Node version v14.19.3
strapi-plugin-import-export-entries 1.6.9
AWS RDS Postgres 14.3

[Final import - Final import.csv](https://github.com/Baboo7/strapi-plugin-import-export-entries/files/9333460/Final.import.-.Final.import.csv)

**Comment by everythinginjs** [comment]
works well with mySQL database. I guess the problem comes from the design system of Postgres.

**Comment by scottydev** [comment]
Having the same issue backing up the default sqlite DB then switching to postgresql. There's a possible fix detailed here but you'll have to get into your psql server and run a query:

https://github.com/strapi/strapi/issues/12493#issuecomment-1044724834

It seems postgres has an internal unique ID/counter you may have to offset by the number of entries from the incoming import. At least that's how I'm interpreting it.

I'm not having luck with it so may just manually copy my data over >_<

**Comment by everythinginjs** [comment]
@scottydev that's right I have also found that, but imagine after each bulk import you should find yourself in the db and fixing counter that's so terrible. I am not expert at DBs but I think there must be somewhat solutions.
