### ISSUE TITLE
[BUG] View is not "refreshed" after importing data

### ISSUE THREAD

**Issue by SalahAdDin** [Baboo7/strapi-plugin-import-export-entries#39]
**Describe the bug**
We think it is more like a missing feature but after importing data, we don't see any data on the view till we refresh the browser.

**To Reproduce**

1. Go to any **Model** in the **Content Manager**.
2. Click on **Import**.
3. Select the file and do the import.
4. Look at the success toast and the empty list.

**Expected behavior**
It should show all the loaded data just after importing it with no need to refresh the browser.

**Screenshots**
This is after importing all data in **Tags**
https://user-images.githubusercontent.com/5034215/184628761-b9509512-a301-4a76-b18d-79c9aeceb875.mov
As you can see, we have to refresh the browser to view the imported data.

**Additional context**

**Comment by Baboo7** [comment]
This is now fixed in version `1.12.0`
