### ISSUE TITLE
[BUG] Export doesn't work with following component schema 

### ISSUE THREAD

**Issue by thousandsofraccoons** [Baboo7/strapi-plugin-import-export-entries#40]
**Describe the bug**
```
{
  "collectionName": "components_product_prices",
  "info": {
    "displayName": "price",
    "icon": "money-bill-wave",
    "description": ""
  },
  "options": {},
  "attributes": {
    "price": {
      "type": "integer",
      "required": true,
      "min": 0
    },
    "unit": {
      "type": "string",
      "required": true
    },
    "stock": {
      "type": "integer",
      "required": true,
      "min": 0
    }
  }
}
```

**To Reproduce**

1. Add schema, 
2. Create test data
3. Try to export

**Expected behavior**
The component data exported

**Screenshots**
![image](https://user-images.githubusercontent.com/33694447/184926681-3318fab6-618a-41c3-86b4-a749a6e9cce9.png)

**Additional context**

**Comment by Baboo7** [comment]
Hey @thousandsofraccoons, FYI I just published version `1.15.0` where v2 of export/import has been implemented. It's a beta still but it showed more stable results than the v1 on the test data I used. Export v2 is accessible in the export modal by selecting the export format `JSON (v2)` / import v2 is detected automatically from the structure of the provided data file.

I would love to have your feedback on this new version. Feel free to join the [discord server](https://discord.gg/cGRJh7M7) of the project I just opened 😌
