### ISSUE TITLE
[FEATURE] exporting based on user selection

### ISSUE THREAD

**Issue by everythinginjs** [Baboo7/strapi-plugin-import-export-entries#44]
@Baboo7  Thanks for the time you set aside for developing the plugin,
Sometimes we want to export a fixed amount of data but with this plugin whether you like it or not gives you whole data as CSV or JSON would be amazing to select just the data that you would like to export.

**Comment by Baboo7** [comment]
There is a filter feature implemented based on the filters of the content type page. You can set these filters and check the option _apply sort and filters to exported data_ in the export modal. Have you tried it?

**Comment by everythinginjs** [comment]
@Baboo7  thanks I have not tried that, great feature. 🙌

**Comment by Baboo7** [comment]
[Section about filtering and sorting](https://github.com/Baboo7/strapi-plugin-import-export-entries#filtering-and-sorting) added in the doc
