### ISSUE TITLE
[FEATURE] How to export [media] programmatically?

### ISSUE THREAD

**Issue by matepaiva** [Baboo7/strapi-plugin-import-export-entries#48]
**Is your feature request related to a problem? Please describe.**
I need to export the media programmaticaly to finish my migration process, so I can replace the old url with the new one in text contents.

**Describe the solution you'd like**
- I don't know if it is possible to export `media` specifically.
- It would be interesting to have documented how to export any content-type programmatically.

**Describe alternatives you've considered**
I would try to export via dashboard, but it is not possible when the `slug` is `media`.

**Comment by Baboo7** [comment]
@matepaiva new version out `1.14.1`!

Media can be exported programatically (see the [Service section](https://github.com/Baboo7/strapi-plugin-import-export-entries#services) of the doc).
