### ISSUE TITLE
[BUG] 405 response when trying to export from the dasboard

### ISSUE THREAD

**Issue by anghiulian** [Baboo7/strapi-plugin-import-export-entries#49]
**Describe the bug**
Installed and configured the plugin as per the readme file.
Strapi v4.0.6
Node 16.13.2

**To Reproduce**

1. Go to Content manager
2. Click on export
3. Pop-up appears with Export failed: An unexpected error occurred while exporting your data.
4.Investigating the request reveals that the error is actually 405 Method not allowed.

**Comment by Baboo7** [comment]
Version `1.4.1`is out, can you try if this version solves the issue ?

If it does not, please post a log or a screenshot of the error

**Comment by anghiulian** [comment]
@Baboo7 that seems to have done the trick :) thanks for the update!
