### ISSUE TITLE
[BUG] Import doesn't seem to be working

### ISSUE THREAD

**Issue by schimini** [Baboo7/strapi-plugin-import-export-entries#5]
**Describe the bug**
The export function seems to be working properly in both CSV and JSON but importing it, despite showing the success window, doesn't actually persist the imported data.

Thanks in advance for the effort put into the plugin!

**To Reproduce**
1. Go to a collection
2. Create an entry
3. Export collection
4. Import file (changing entity ID, or deleting the previously created one)
5. Refresh page

**Expected behavior**
Import should add the imported data to the database

**Additional context**

package,json
` "@strapi/plugin-graphql": "4.1.10",
    "@strapi/plugin-i18n": "4.1.10",
    "@strapi/plugin-users-permissions": "4.1.10",
    "@strapi/provider-upload-aws-s3": "4.1.10",
    "@strapi/strapi": "4.1.10",
    "caniuse-lite": "1.0.30001323",
    "pg": "8.6.0",
    "sharp": "^0.29.3",
    "strapi-plugin-import-export-entries": "^1.3.4"`

**Comment by Baboo7** [comment]
I just pushed a fix with version `1.3.6`, import should be working now.
I added an [example on how import behaves](https://github.com/Baboo7/strapi-plugin-import-export-entries#usage) in the doc.

**Comment by schimini** [comment]
@Baboo7 Thank you! ( I must say, very cool to have a fix that fast)

I'll test the plugin again tomorrow and let you guys know if it's fixed.

Thank you!

**Comment by florianmarical** [comment]
Hello,
I just test and  that work for me. Thank you ! It's very cool plugin and nice job !

**Comment by schimini** [comment]
Confirmed. Thanks again @Baboo7 !
