### ISSUE TITLE
[FEATURE] Add a contribution guide to the repository.

### ISSUE THREAD

**Issue by sinamoradi1375** [Baboo7/strapi-plugin-import-export-entries#51]
Hey there, I'm forking the repo and I'm trying to run this plugin in development but there isn't any contribution guide. I cannot exactly get it up and running. Could you please guide me towards the way?

**Comment by sinamoradi1375** [comment]
Here's the thing. I've copied all of the repo's files and directories into a new Strapi app under `src/plugins/import-export` and added the required resolve statement in `config/plugins.js`. Then I `cd`ed into the plugin folder and did a `yarn install`. After that, I followed the README.md file and added monaco webpack plugin to `src/admin/webpack.config.js`. Thought it would work this way. I also increased the json input max limit in the Strapi middleware to 10 MB. Here I run `yarn build` but it gives an error saying the monaco plugin is not installed. I also installed it in the main Strapi project, but it led to another error that I thought might not be the correct way and is not worth more digging. Would you please share with us how to setup the development environment?

**Comment by sinamoradi1375** [comment]
Now I've tried to move the dependencies to the main Strapi and here's the catch, when I try to export, it returns 405 status code from `POST /import-export-entries/export/contentTypes`.

**Comment by Baboo7** [comment]
There is no contribution guide at the moment but I agree it would be great. I'm currently working on having tests on the project for quality. 

I reopen this issue to keep track of it

**Comment by Baboo7** [comment]
@sinamoradi1375 I setup a repo to contribute more easily. See the [Contribute section](https://github.com/Baboo7/strapi-plugin-import-export-entries#contribute) of the doc
