### ISSUE TITLE
[BUG] pathToPlugin is not defined

### ISSUE THREAD

**Issue by oleghalin** [Baboo7/strapi-plugin-import-export-entries#55]
**Describe the bug**
After plugin installation i cannot use it because no strapi block in your package.json

**To Reproduce**
Not required

**Expected behavior**
Plugin works

**Comment by oleghalin** [comment]
For some reason yarn didnt install plugin after add. Sorry.

**Comment by Baboo7** [comment]
No worries. I appreciate the report and the reactivity 😌
