### ISSUE TITLE
[BUG] Duplicate entries are imported 

### ISSUE THREAD

**Issue by SaintNandarOo** [Baboo7/strapi-plugin-import-export-entries#57]
Describe the bug
When I import to a collection type with a csv file that contains duplicate value for "Unique field," it imports and creates the duplicate entries without showing any error.

To Reproduce

1. Create a collection type that contains the "Unique field"
2. Prepare CSV file with duplicate value for "Unique field"
3. Import the file and you can see that it will create duplicate entries 

Expected behavior
Skip importing the duplicate entries if "Unique field" is defined and show a dialog box for skip entries after importing.

**Comment by nicoXXXXXtitan** [comment]
+1 
I am the same problem.

**Comment by SaintNandarOo** [comment]
Hey @nicoXXXXXtitan the plugin developer published version 1.15.0 and we can choose the "Id Field" as "Unique field" when we import.

**Comment by nicoXXXXXtitan** [comment]
Great !
I had missed this option. Thanks a lot !
