### ISSUE TITLE
[BUG] Importing does not seem to work although showing success message

### ISSUE THREAD

**Issue by jasonbutt** [Baboo7/strapi-plugin-import-export-entries#60]
**Describe the bug**
The export function seems to be working properly in both CSV and JSON but importing it, despite showing the success window, doesn't seem to load the imported data.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a collection
2. Create an entry
3. Export collection
4. Import file (changing entity ID, or deleting the previously created one)
5. Refresh the page

**Expected behaviour**
Import should add the imported data to the database

**Screenshots**

**Additional context**
package.json
    "@chartbrew/plugin-strapi": "^0.2.7",
    "@strapi/icons": "^1.2.0",
    "@strapi/plugin-i18n": "4.1.8",
    "@strapi/plugin-users-permissions": "4.1.8",
    "@strapi/strapi": "4.1.8",
    "better-sqlite3": "7.4.6",
    "pg": "^8.7.3",
    "pg-connection-string": "^2.5.0",
    "sqlite3": "5.0.2",
    "strapi-plugin-import-export-entries": "^1.14.1",
    "uuid": "^8.3.2"

A similar issue that seems to be fixed in a previous version but seeing the same problem in Closed Issue #5

**Comment by Baboo7** [comment]
Hey @jasonbutt. I just published version `1.15.0` where export/import v2 has been implemented. It's a beta still but it showed more stable results than the v1 on the test data I used. Export v2 is accessible in the export modal by selecting the export format `JSON (v2)`; import v2 is detected automatically from the structure of the provided data file.

I would love to have your feedback on this new version. Feel free to join the [discord server](https://discord.gg/cGRJh7M7) of the project I just opened 😉

**Comment by jasonbutt** [comment]
Awesome. Yes, updated to 1.15.0 and the export and import using JSON V2 fixed my issue.  I definitely like the JSON import option. I'll be playing around with it more over the next few weeks and will provide feedback as I can on Discord. Appreciate the update.
