### ISSUE TITLE
[BUG] Applied filters doesnt affect export

### ISSUE THREAD

**Issue by oleghalin** [Baboo7/strapi-plugin-import-export-entries#65]
**Describe the bug**
Applied filters doesnt affect export

**To Reproduce**
Apply any filter to make content list empty
Click export

**Expected behavior**
Empty csv

**Comment by Baboo7** [comment]
Hi @oleghalin , have you checked the option to apply sort and filter to exported data?

**Comment by oleghalin** [comment]
Wow, sorry, you are right.  Thanks.
