### ISSUE TITLE
[BUG] Dependency on import

### ISSUE THREAD

**Issue by DenisBalan** [Baboo7/strapi-plugin-import-export-entries#66]
Suppose you have `restaurant` and  `dishes` and dishes have `belong_to` field which links to a specific restaurant.
Right now, on import its throwing an error like foreign key on `dishes_restaurant_links` table.

To fix this, i just reimport same data, and it creates links between collections.

So as a permanent resolution, better to check depedencies on import and start from ground (no dependencies to other tables) to the most top one.

**Comment by Baboo7** [comment]
Interesting. Generating a dependency graph may not work in cases where 2 collections reference one another. It may work if entites are created first without relations, and then updated with the right ones

**Comment by Baboo7** [comment]
@DenisBalan version `1.16.2` is published and fixes the issue. Feel free to tell me if it doesn't work as expected
