### ISSUE TITLE
[HELP] Strapi relation collection

### ISSUE THREAD

**Issue by Hertak** [Baboo7/strapi-plugin-import-export-entries#67]
Hi, i try to found a forum or wiki if any know one i appreciate the link.
I need help with import. I have a items collection and a category collection with a many to many relationship. How can i import the items? Thanks

**Comment by Baboo7** [comment]
Hey @Hertak , you're in the right place (you can also join the discord where I plan to handle such requests in a near future, see the readme for link). What are you struggling with?

**Comment by Hertak** [comment]
Hi, thanks for answer. 
I have the items on my Strapi this is a collection and in other collection i have the category (Note: i use word category but is more a tag sistem) my problem is that i can´t assign the correct category.  See an example of the cvs
`nombre,categorias,direccion,telefono
Melisa Schwab Inmobiliaria,Agencia inmobiliaria,Gral. Paz 2888,02284 35-5955
Saez Mauro Inmobiliaria,Agencia inmobiliaria,Olavarría,02284 41-4134
Alloggia Propiedades,Agencia inmobiliaria,"Micro Centro, 25 de Mayo 2420, B7400DJF Olavarría, Provincia de Buenos Aires",44-5420
`
How can i make the cvs to populate the categories? Not always is the same but every item need one. Now on my Strapi i have a relation many to many but can be many to one.  Thanks for the help.

**Comment by Baboo7** [comment]
Do you have to use CSV? If not give a try the json v2 export. It works better and is my focus now

**Comment by Hertak** [comment]
Thanks. I use csv because is more flexible, for me. The data i get in a csv. I try convert and see what happend. many thanks

**Comment by Hertak** [comment]
I try but i don´t understand the correct structure of the json or the csv. I need put the field of relation, the filed to be created on the other collection?

**Comment by Baboo7** [comment]
for the json v2 the structure is still to be documented. Here is an example of the file structure based on your data. See the comments for details and how to customize this json according to your data (you will have to remove the comments to have a valid json file)

```js
{
	"version": 2,
	"data": {
                // Every collection can have a key added to `data`.
                // Here insert the name of your categories collection.
		"api::your-categories.your-categories": {
			"1": {
				"id": 1,
				"name": "Agencia inmobiliaria"
			}
                },
                // Here insert the name of your data collection.
		"api::your-collection.your-collection": {
			"1": {
				"id": 1,
				"nombre": "Melisa Schwab Inmobiliaria",
                                // Relations are represented by their id.
				"categorias": [1],
				"direccion": "Gral. Paz 2888",
				"telefono": "02284 35-5955"
			},
			"2": {
				"id": 2,
				"nombre": "Mauro Inmobiliaria",
				"categorias": [1],
				"direccion": "Olavarría",
				"telefono": "02284 41-4134"
			},
			"3": {
				"id": 3,
				"nombre": "Alloggia Propiedades",
				"categorias": [1],
				"direccion": "Micro Centro, 25 de Mayo 2420, B7400DJF Olavarría, Provincia de Buenos Aires",
				"telefono": "44-5420"
			}
                }
	}
}
```

**Comment by Hertak** [comment]
Many Thanks, this works for me.
