### ISSUE TITLE
[FEATURE] Set imported items status to published

### ISSUE THREAD

**Issue by jcAtRsi** [Baboo7/strapi-plugin-import-export-entries#68]
Perhaps this is already possible, but the ability to have imported items set to published would be very helpful.

**Comment by Baboo7** [comment]
Hey @jcAtRsi this indeed already possible. You just have to specify the published date for an entry

**Comment by jcAtRsi** [comment]
That does indeed work, thank you!  When importing data, should the created by & last update by fields be set to the id of the user doing the import? Or is that data that should be added to the csv/json as well?  Thanks again for your help, and great job on the plugin 🏆

**Comment by Baboo7** [comment]
Your welcome 😌 you don't have to specify the user, it will be the one importing the data. I appreciate the feedback!
