### ISSUE TITLE
[FEATURE] Node 18 support

### ISSUE THREAD

**Issue by mattia85** [Baboo7/strapi-plugin-import-export-entries#70]
Hello,
please update package.json engines section to node 18 if it's supported.

I'm getting the following error running `yarn`

`error strapi-plugin-import-export-entries@1.16.2: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.11.0"`

Thank you

**Comment by gh-kdk** [comment]
ref: #75 

It seems to work fine with node 18.

**Comment by Baboo7** [comment]
The plugin is enabled for node `18` in the new version `1.17.1`
