### ISSUE TITLE
[BUG] Updating with missing columns deletes relation data

### ISSUE THREAD

**Issue by rhd-developers** [Baboo7/strapi-plugin-import-export-entries#72]
**Describe the bug**
Say I have a CSV with only id and title, I want to update all article entries with this id with the provided title, and not touch the other fields. I have multiple reference fields (images and other collections) and they are all deleted if I do this (not the referenced entities themselves, but the relation field within the article). Non-relation fields are untouched, however.

**Expected behavior**
Don't delete data if the column is not provided, or give an option to how to deal with missing columns.

**Comment by Baboo7** [comment]
Hey @rhd-developers have you tried the new json v2 format? It shows more consistent results that csv/json v1

**Comment by Baboo7** [comment]
I confirm that json v2 format supports partial update

**Comment by matepaiva** [comment]
@Baboo7 just a doubt: how to use the v2 format while updating via API? Where do I set `version: 2`? Thank you!

**Comment by Baboo7** [comment]
`version: 2` should be specified in the content of the file, at the same level of the `data` property. See the README for more details
