### ISSUE TITLE
Node.js 18 compatibility

### ISSUE THREAD

**Issue by gh-kdk** [Baboo7/strapi-plugin-import-export-entries#75]
Hi. Strapi 4.4 supports node.js 18 via "engines" directive in package.json. This plugin still holds to node.js 16 which gives this warning when installing packages on node.js 18:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'strapi-plugin-import-export-entries@1.16.2',
npm WARN EBADENGINE   required: { node: '>=12.x.x <=16.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.11.0', npm: '8.19.2' }
npm WARN EBADENGINE }
```

Is it safe to run your plugin on node.js 18?
If so could you update the "engines" directive to match the Strapis one?

TIA and thank you for providing this plugin!
Best regards.

**Comment by Baboo7** [comment]
Hey @gh-kdk thanks for the feedback. This issue has been mentioned here https://github.com/Baboo7/strapi-plugin-import-export-entries/issues/70. Since I have limited ressources I'll update the engine so you can give it a try

**Comment by gh-kdk** [comment]
Closing as this is a duplicate of #70.
