### ISSUE TITLE
[BUG] Import v2 fails incorrectly on RegEx Validation

### ISSUE THREAD

**Issue by JWesorick** [Baboo7/strapi-plugin-import-export-entries#80]
**Describe the bug**
I have a slug field that has a "RegExp pattern" validation of `^[A-Za-z0-9\-\_]*$`. When trying to import (v2) an error is thrown:

```json
[
  {
    "error": "slug must match the following: \"/^[A-Za-z0-9\\-\\_]*$/\"",
    "data": {
      "id": 157,
      "slug": "abc-123",
      ...
    }
  }
]
```

**To Reproduce**

1. Create a Collection type with a field with the RegEx pattern of the one above.
2. Create an valid object in that collection.
3. Export the object.
4. Import the object.

**Expected behavior**

Object should import without error.

**Screenshots**
![Screen Shot 2022-11-11 at 3 16 54 PM](https://user-images.githubusercontent.com/801062/201296436-6700fa83-eace-448a-8f65-4bbfa2af509c.png)

**Additional context**

**Comment by Baboo7** [comment]
Interesting. Since I'm using the content type service to create/update entries, validation should be operational when importing content. Can you share the schema you're trying to import and the related json v2 file?

**Comment by JWesorick** [comment]
Ok this if my fault. I had `-` (U+002D) in a slug name and `–` (U+2013) in the regex.
