### ISSUE TITLE
[FEATURE] Can't restore data received by api request

### ISSUE THREAD

**Issue by alrdigt** [Baboo7/strapi-plugin-import-export-entries#82]
When me get export data by curl by POST route /api/import-export-entries/content/export/contentTypes with "exportFormat": "json-v2" content incudes something like: "{"data":"{\n\t\"version\": 2,\n\t\"data\": {\n\t\t\"api::articles1.articles1\": {\n\t\t\t\..." in this format impossibe import data back. Can you add function to parse Json  that's look like in modal window in browser for keep functionality to restore data, that was received by api request from bash script, for example?

**Comment by Baboo7** [comment]
@alrdigt import api is described in the README of the project. It should work as expected today since this issue has been opened a long time ago. I'm closing it for now
