### ISSUE TITLE
[BUG] Click check "export format" strapi server error

### ISSUE THREAD

**Issue by DanielZhui** [Baboo7/strapi-plugin-import-export-entries#83]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44571398/203728539-d49cc753-5d89-4662-a74d-29a851cf30ff.png)

**Additional context**

**Comment by Baboo7** [comment]
I could not reproduce the issue with the very few information you gave. I'm closing this issue for now.
