### ISSUE TITLE
[BUG] No content on page when activating this plugin

### ISSUE THREAD

**Issue by landoephan** [Baboo7/strapi-plugin-import-export-entries#84]
**Describe the bug**
I'm getting an error when I go from the content manager tab to the Content-Type builder tab. The whole page just turns white. When I reload the page it's loading as expected. The same result I'm also getting when I click on the dropdown field to change the language inside the content manager tab. When I deactivate the plugin it works fine.

**To Reproduce**

1. Go to content manager inside the admin panel
2. Click on Content-Type Builder
3. See a white page and an error in the console

**Expected behavior**
The page loads correctly and I can interact with the language switcher

**Screenshots**
![image](https://user-images.githubusercontent.com/43780811/204272039-a68a02fc-3636-4f1f-b603-be35bf193dca.png)

Result:
![image](https://user-images.githubusercontent.com/43780811/204272659-811dd374-bc8f-4145-adba-24bbda8045f4.png)

**Additional context**
Error message from browser console:
```
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at g (main.1e108730.js:34:16287)
    at m (main.1e108730.js:2552:23941)
    at f (main.1e108730.js:2552:19407)
    at il (content-type-builder.533b7fe6.chunk.js:176:21364)
    at Nu (main.1e108730.js:3594:54845)
    at $n (main.1e108730.js:3598:9231)
    at Pd (main.1e108730.js:3598:991)
    at Nh (main.1e108730.js:3598:920)
    at Yf (main.1e108730.js:3598:771)

Uncaught Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at h.render (6593.efa5abce.chunk.js:86:7285)
    at $c (main.1e108730.js:3594:67938)
    at vg (main.1e108730.js:3594:67721)
    at $n (main.1e108730.js:3598:10254)
    at Pd (main.1e108730.js:3598:991)
    at Nh (main.1e108730.js:3598:920)
    at Yf (main.1e108730.js:3598:771)
    at Td (main.1e108730.js:3596:11158)
    at main.1e108730.js:3594:39639
    at a.unstable_runWithPriority (main.1e108730.js:3626:3954)
```

My package.json

```
  "dependencies": {
    "@notum-cz/strapi-plugin-content-versioning": "^0.4.7",
    "@strapi/plugin-i18n": "4.5.2",
    "@strapi/plugin-users-permissions": "4.5.2",
    "@strapi/strapi": "4.5.2",
    "better-sqlite3": "7.4.6",
    "monaco-editor-webpack-plugin": "^7.0.1",
    "patch-package": "^6.5.0",
    "pg": "^8.8.0",
    "strapi-plugin-config-sync": "^1.0.4",
    "strapi-plugin-import-export-entries": "^1.18.0"
  },
```

**Comment by landoephan** [comment]
When I disable the i18n plugin it works, too. So it seems to be a combination from both plugins. When one of them is disabled, everything works fine.

**Comment by lrasata** [comment]
I got this error earlier last week. It is not directly linked to this plugin but the dependencies. A few days ago, I removed yarn.lock and node_modules and installed everything again and it worked. This error just disappeared.

**Comment by landoephan** [comment]
unfortunately, that didn't help for me, I'm still getting this error.

See also https://github.com/strapi/strapi/issues/14993

**Comment by Baboo7** [comment]
@landoephan @lrasata the i18n plugin is correctly handled today. Since this issue has been opened a long time ago, I'm closing it for now
