### ISSUE TITLE
[BUG] CSV import with one-to-many relation doesn't work 

### ISSUE THREAD

**Issue by Ternowy** [Baboo7/strapi-plugin-import-export-entries#85]
**Describe the bug**
When importing the CSV file with array of ids occurs following error:
FOREIGN KEY constraint failed

**To Reproduce**

1. Go to 'Content Manager'
2. Choose content type with multiple relations
3. Import CSV file with following data
```
id,name,disease_symptoms
1,Test,"[1,3]"
```
5. See error

**Expected behavior**
It is expected to see the relations

**Screenshots**
![image](https://user-images.githubusercontent.com/35680667/204289029-d0c318f1-9866-44e5-8013-05c89a282535.png)

**Additional context**
Personal opinion:
Deprecation of CSV prevents collaboration between tech and non-tech people

**Comment by Ternowy** [comment]
I close the issue, since I was using wrong IDs

**Comment by Baboo7** [comment]
Self disciplined! I appreciate it
