### ISSUE TITLE
[FEATURE] Strapi Internationalization for Translations

### ISSUE THREAD

**Issue by cawoodm** [Baboo7/strapi-plugin-import-export-entries#87]
**Is your feature request related to a problem? Please describe.**
Does this plugin support [Strapi Internationalization](https://strapi.io/features/internationalization), if so, could this be added so we can upload content in multiple languages?

**Comment by boarder22lb** [comment]
Any action items on this? I would +1 this.

**Comment by Baboo7** [comment]
Yes this plugin supports the internationalization plugin. I just published this massive new version 1.19.0, so give it a try
