### ISSUE TITLE
[BUG] Can't import entire db when using postgres

### ISSUE THREAD

**Issue by landoephan** [Baboo7/strapi-plugin-import-export-entries#89]
**Describe the bug**
When I export the entire db from a postgres db and try to import it again I get a 403 error on `POST /import-export-entries/import` and a 500 error afterwards on `GET http://localhost:1337/import-export-entries/import/model-attributes/custom:db`

The logs from my strapi application look like this:
```
[2022-12-08 14:43:41.957] error: Cannot read properties of undefined (reading 'attributes')
TypeError: Cannot read properties of undefined (reading 'attributes')
    at getModelAttributes (.../node_modules/strapi-plugin-import-export-entries/server/utils/models.js:89:46)
    at Object.getModelAttributesEndpoint [as getModelAttributes] (.../node_modules/strapi-plugin-import-export-entries/server/controllers/admin/import-controller/get-model-attributes.js:8:26)
    at dispatch (.../node_modules/koa-compose/index.js:42:32)
    at returnBodyMiddleware (.../node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:24)
    at dispatch (.../node_modules/koa-compose/index.js:42:32)
    at policiesMiddleware (.../node_modules/@strapi/strapi/lib/services/server/policy.js:24:11)
    at dispatch (.../node_modules/koa-compose/index.js:42:32)
    at .../node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:33:12
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-12-08 14:43:46.827] http: POST /import-export-entries/import (37 ms) 403
[2022-12-08 14:43:46.857] error: Cannot read properties of undefined (reading 'attributes')
TypeError: Cannot read properties of undefined (reading 'attributes')
    at getModelAttributes (.../node_modules/strapi-plugin-import-export-entries/server/utils/models.js:89:46)
    at Object.getModelAttributesEndpoint [as getModelAttributes] (.../node_modules/strapi-plugin-import-export-entries/server/controllers/admin/import-controller/get-model-attributes.js:8:26)
    at dispatch (.../node_modules/koa-compose/index.js:42:32)
    at returnBodyMiddleware (.../node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:24)
    at dispatch (.../node_modules/koa-compose/index.js:42:32)
    at policiesMiddleware (.../node_modules/@strapi/strapi/lib/services/server/policy.js:24:11)
    at dispatch (.../node_modules/koa-compose/index.js:42:32)
    at .../node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:33:12
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

In the browser console I'm getting the following error messages:
```
main.a5adda14.js:9121          GET http://localhost:1337/import-export-entries/import/model-attributes/custom:db 500 (Internal Server Error)
...
main.a5adda14.js:9121 Uncaught (in promise) Error: Internal Server Error
    at main.a5adda14.js:9121:12290
(anonymous) @ main.a5adda14.js:9121
...
main.a5adda14.js:9121          POST http://localhost:1337/import-export-entries/import 403 (Forbidden)
Tr @ main.a5adda14.js:9121
...
main.a5adda14.js:9121          GET http://localhost:1337/import-export-entries/import/model-attributes/custom:db 500 (Internal Server Error)
...
main.a5adda14.js:9121 Uncaught (in promise) Error: Internal Server Error
    at main.a5adda14.js:9121:12290
```

Three requests are made:
1. 
```
Request URL: http://localhost:1337/import-export-entries/import/model-attributes/custom:db
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:1337
Referrer Policy: no-referrer
```
2.
```
Request URL: http://localhost:1337/import-export-entries/import
Request Method: POST
Status Code: 403 Forbidden
Remote Address: 127.0.0.1:1337
Referrer Policy: no-referrer
```
3.
```
Request URL: http://localhost:1337/import-export-entries/import/model-attributes/custom:db
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:1337
Referrer Policy: no-referrer
```

**To Reproduce**

1. Go to http://localhost:1337/admin/plugins/import-export-entries
2. Click on export --> fetch data --> Download file --> save file
3. Click on import --> select the saved file --> import
4. See error in browser console and application logs

**Expected behavior**
The import from a complete db export works. The data is imported in the database and visible in the admin panel

**Additional context**
Version: "strapi-plugin-import-export-entries": "^1.18.0"

database version: "pg": "^8.8.0"

I'm a superuser in my postgres db

**Comment by mikebcbc** [comment]
I'm encountering the same issue.

**Comment by mikebcbc** [comment]
@landoephan one workaround that just worked for me is individually importing/exporting each model instead of the whole DB at once. I was able to import it all, just a tad more tediously. Maybe that'll work for you too?

**Comment by landoephan** [comment]
@mikebcbc I tried that, too, but then I have another problem, see https://github.com/Baboo7/strapi-plugin-import-export-entries/issues/88. Maybe you could check, if you're encountering that problem, too?

**Comment by VrTech** [comment]
Same problem here cannot import when using postgres

**Comment by gfsd3v** [comment]
Same here.

**Comment by cooperwfloyd** [comment]
same problem here. exporting from Postgres is successful, but when importing locally into the default SQLite database is when that same `TypeError: Cannot read properties of undefined (reading 'attributes') at getModelAttributes` error comes up

**Comment by mbkkong** [comment]
+10

**Comment by hpmax00** [comment]
+1

**Comment by sts-ryan-holton** [comment]
Experiencing the same thing

**Comment by JoshuaRobertson** [comment]
I'm experiencing the same issue as a Super Admin. After selecting a file it throws a `500` error for `custom:db` and then when attempting an import it results in a `403` error. The only difference for my project is I'm using MariaDB instead of postgres.

Could this be related to the recent [Strapi CMS update](https://github.com/strapi/strapi/releases/tag/v4.5.4) and a change in user permissions?

**Comment by rgouzal** [comment]
> @landoephan one workaround that just worked for me is individually importing/exporting each model instead of the whole DB at once. I was able to import it all, just a tad more tediously. Maybe that'll work for you too?

When you imported the DB , what deepness you set or you set it to none?

**Comment by landoephan** [comment]
I can't test it at the moment since strapi always crashes after a while of loading. I guess my database became too big already

**Comment by rgouzal** [comment]
> I can't test it at the moment since strapi always crashes after a while of loading. I guess my database became too big already

I did came across that too

**Comment by cyruskorn** [comment]
+1

**Comment by oyenigun** [comment]
Same here.
When i tried to export and import on Content Manager for one collection it succeed. 
Export whole database is working but  import whole database is not working.

**Comment by molul** [comment]
+1. Production db is postgres, development is sqlite, I can export from production but can't import to development. I see the same errors mentioned in the first post.

**Comment by rtkac** [comment]
Same issue here.
Export from postgres is working fine, but import the same exported JSON to postgres failed.
`error: Cannot read properties of undefined (reading 'attributes')`

**Comment by Baboo7** [comment]
This issue is fixed in version 1.19.0!

**Comment by molul** [comment]
I confirm this is working for me now. Thanks! <3

**Comment by rtkac** [comment]
@Baboo7 thanks for the update.

I can see 500 error response while uploading:
`{"data":null,"error":{"status":500,"name":"InternalServerError","message":"Internal Server Error"}}`

Do you know what could be a problem?

Thanks!

**Comment by Baboo7** [comment]
https://github.com/Baboo7/strapi-plugin-import-export-entries/issues/113
