### ISSUE TITLE
[FEATURE] Role permission for button appearance

### ISSUE THREAD

**Issue by skyclb** [Baboo7/strapi-plugin-import-export-entries#9]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want to be able to hide the buttons for the role author.

**Describe alternatives you've considered**
Don't think there are alternatives.

**Additional context**
None.

**Comment by Baboo7** [comment]
Why specifically for the role author?

**Comment by dbugshe2** [comment]
Hi, So I have a similar concern, but in my case, I want to know of the possibility to enable just one of the buttons, not necessarily based on role. I just want to be able to export without importing, as I don't actually want the users to import data at once.

**Comment by Baboo7** [comment]
Interesting. An option to activate/deactivate buttons from the plugin home page could do the trick

**Comment by SalahAdDin** [comment]
> Interesting. An option to activate/deactivate buttons from the plugin home page could do the trick

Or giving permissions like other plugins have, is it hard?

**Comment by skyclb** [comment]
> @skyclb Why specifically for the role author?

Because i would like to prevent content editors to import or export (import far more dangerous). I like to show them only to roles above author, because those are designated for developers which should see them.

Sorry for late reply.

**Comment by pranavks** [comment]
+1. this is not enterprise level production-ready until we can restrict the access to specific user roles.

**Comment by r0emek** [comment]
+1

**Comment by SalahAdDin** [comment]
> +1. this is not enterprise level production-ready until we can restrict the access to specific user roles.

This is not an enterprise plugin.

**Comment by Baboo7** [comment]
All right folks, the next feature prioritized is this one

**Comment by Baboo7** [comment]
Version 1.20.0 is out with a first version of access controls. Tell me folks if it suits your needs
