### ISSUE TITLE
[BUG] Strapi Admin Panel crashes when using the enumeration field with this plugin in latest version (4.5.5)

### ISSUE THREAD

**Issue by rubek-joshi** [Baboo7/strapi-plugin-import-export-entries#90]
**Describe the bug**
Strapi's admin panel crashes if I interact with the Enumeration field (i.e. open the dropdown) **when this plugin is enabled** in **Strapi version `4.5.5`**

**To Reproduce**

1. Create a collection/single type with an enumeration field.
2. Populate the collection/single type through the Content Manager.
3. When you try to open the dropdown, you'll see the error.

**Expected behavior**
Able to interact with the enumeration field without any crash.

**Screenshots**
[You can check out this video](https://www.loom.com/share/fb7e0b785f3d45e39ebfa706f3175f55)

**Additional context**
When I do remove this plugin, there is no crash hence I am convinced that it's a bug with this plugin although I have no idea why this plugin should affect the Enumeration field.

**Comment by Baboo7** [comment]
@rubek-joshi @cmolendijk I couldn't reproduce the bug with version `1.19.1`
