### ISSUE TITLE
[BUG]  Importing causing Cannot read properties of undefined (reading 'attributes') error

### ISSUE THREAD

**Issue by jmarchi** [Baboo7/strapi-plugin-import-export-entries#92]
**Describe the bug**
This is all in local development on a new instance of Strapi created two days ago, everything should be set to default. I have not uploaded any media yet. 

Attempting to try a simple export/import case but I am getting an error while importing via the "Import Export" in the side panel (collection specific export/import was successful on the same collections). There is no feedback from the UI other than the modal flashes briefly and there are console logs for uncaught internal server errors. This also happens if importing back to the instance I had exported from immediately after exporting, the behavior appears the same.

`TypeError: Cannot read properties of undefined (reading 'attributes')
at getModelAttributes (/opt/node_modules/strapi-plugin-import-export-entries/server/utils/models.js:89:46)
at Object.getModelAttributesEndpoint [as getModelAttributes] (/opt/node_modules/strapi-plugin-import-export-entries/server/controllers/admin/import-controller/get-model-attributes.js:8:26)
at dispatch (/opt/node_modules/koa-compose/index.js:42:32)
at returnBodyMiddleware (/opt/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:24)
at dispatch (/opt/node_modules/koa-compose/index.js:42:32)
at policiesMiddleware (/opt/node_modules/@strapi/strapi/lib/services/server/policy.js:24:11)
at dispatch (/opt/node_modules/koa-compose/index.js:42:32)
at /opt/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:33:12` 

I'm not sure if this is a potential bug or a misconfiguration somewhere, but also not sure what else to eliminate since it seems to be a simple use case. 

**To Reproduce**
On two instances Strapi from the same repo, exported via the "Import Export" page on sidebar and imported via the same page. 

The import file looks like this 

<img width="464" alt="image" src="https://user-images.githubusercontent.com/4614712/211951456-79955fa5-a195-485a-bd5d-0736cb0a3b01.png">

`{
  "version": 2,
  "data": {
    "plugin::upload.folder": {},
    "plugin::upload.file": {},
    "api::blog-post.blog-post": {
      "1": {
        "id": 1,
        "title": "blog post",
        "content": "blog to be backed up and imported",
        "createdAt": "2023-01-11T23:29:38.608Z",
        "updatedAt": "2023-01-11T23:29:41.508Z",
        "publishedAt": "2023-01-11T23:29:41.505Z",
        "picture": null,
        "createdBy": null,
        "updatedBy": null
      }
    },
    "api::marketing.marketing": {
      "1": {
        "id": 1,
        "name": "entry 1",
        "showit": true,
        "createdAt": "2023-01-12T00:10:02.016Z",
        "updatedAt": "2023-01-12T00:10:02.818Z",
        "publishedAt": "2023-01-12T00:10:02.815Z",
        "createdBy": null,
        "updatedBy": null
      }
    }
  }
}`

**Expected behavior**
Expected to be able to export multiple collections, import the data in another instance and see the data in the collection.

**Comment by hoggworks** [comment]
Piping in to say that I'm experiencing the same issues. I'm also getting an error when I try export via a specific collection:
`Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at main.845f2b4c.js:5:25510
    at Object.useMemo (main.845f2b4c.js:3601:61058)
    at a.useMemo (main.845f2b4c.js:3626:6124)
    at p (main.845f2b4c.js:5:25495)
    at j (main.845f2b4c.js:4415:340)
    at Nu (main.845f2b4c.js:3601:54845)
    at zn (main.845f2b4c.js:3605:9231)
    at Td (main.845f2b4c.js:3605:991)
    at Nh (main.845f2b4c.js:3605:920)`
    
    I can export from the `http://localhost:1337/admin/plugins/import-export-entries` url, but get the import errors on both this url, and when trying to import on a specific collection. This is for a pretty new Strapi instance.

**Comment by gorgsenegger** [comment]
Same here, too.

**Comment by clement-amat** [comment]
I do to have the error, both when trying to import a single type, or from the global Import/Export menu.

My configuration : 
"@strapi/strapi": "4.5.6",
"strapi-plugin-import-export-entries": "^1.18.0"

**Comment by CodeBlocksCreative** [comment]
I have this error too

**Comment by pneff** [comment]
I ran into this today and briefly debugged it. It would appear that the bug only happens if you try to import from the Import Export Plugin screen at `/admin/plugins/import-export-entries` but not if you use the Import button in the Content Manager. So that could work as a workaround for now. I don't know if this will only import one model at a time though, as I currently don't have more than one in my test deployment.

In the error case, there is a network request to `/import-export-entries/import/model-attributes/custom:db`. That results in the plugin trying to look up `custom:db` as if it was a model. I see that this `custom:db` value is intended to be a magic constant indicating that everything should be exported (and probably imported too).

**Comment by claudiomerli** [comment]
> I ran into this today and briefly debugged it. It would appear that the bug only happens if you try to import from the Import Export Plugin screen at `/admin/plugins/import-export-entries` but not if you use the Import button in the Content Manager. So that could work as a workaround for now. I don't know if this will only import one model at a time though, as I currently don't have more than one in my test deployment.
> 
> In the error case, there is a network request to `/import-export-entries/import/model-attributes/custom:db`. That results in the plugin trying to look up `custom:db` as if it was a model. I see that this `custom:db` value is intended to be a magic constant indicating that everything should be exported (and probably imported too).

I ran in this error too and I found the same issues. It try to find a key called custom:db which return undefined. Tied with strapi 4.4.3 and 4.5.1

**Comment by dejanspilot** [comment]
I'm pretty sure that it has to do something with the transformer plugin, if you disable the transformer it should do the job, but it still needs a fix for this

**Comment by bodouralrashidi** [comment]
> I'm pretty sure that it has to do something with the transformer plugin, if you disable the transformer it should do the job, but it still needs a fix for this

Can you please elaborate on your meaning of  disable transformer ? and if worked with u can you guide on the steps?

**Comment by pranavks** [comment]
i have the same issue

**Comment by ericruiz-developer** [comment]
> I ran into this today and briefly debugged it. It would appear that the bug only happens if you try to import from the Import Export Plugin screen at `/admin/plugins/import-export-entries` but not if you use the Import button in the Content Manager. So that could work as a workaround for now. I don't know if this will only import one model at a time though, as I currently don't have more than one in my test deployment.
> 
> In the error case, there is a network request to `/import-export-entries/import/model-attributes/custom:db`. That results in the plugin trying to look up `custom:db` as if it was a model. I see that this `custom:db` value is intended to be a magic constant indicating that everything should be exported (and probably imported too).

This worked for me! I'm fine with this and wouldn't even consider it a work-around right now. It's just importing from another page. Thanks for this info! Main import from plugin still needs a fix.

**Comment by andreineamtu** [comment]
I have the same issue. Any help?

**Comment by avrame** [comment]
I'm also seeing this issue

**Comment by daaaaaavis** [comment]
> I ran into this today and briefly debugged it. It would appear that the bug only happens if you try to import from the Import Export Plugin screen at `/admin/plugins/import-export-entries` but not if you use the Import button in the Content Manager. So that could work as a workaround for now. I don't know if this will only import one model at a time though, as I currently don't have more than one in my test deployment.
> 
> In the error case, there is a network request to `/import-export-entries/import/model-attributes/custom:db`. That results in the plugin trying to look up `custom:db` as if it was a model. I see that this `custom:db` value is intended to be a magic constant indicating that everything should be exported (and probably imported too).

Thank you for this, I was pulling my hair out of import not working. 
It also works with relations and multiple types. 🎉

**Comment by Baboo7** [comment]
@pneff @avrame @andreineamtu @jmarchi @hoggworks This bugged is now fixed in version 1.19.0. @pneff targeted the issue 👍
