### ISSUE TITLE
[BUG] Cannot find module 'request'

### ISSUE THREAD

**Issue by diacu** [Baboo7/strapi-plugin-import-export-entries#96]
**Describe the bug**
`request` was replaced with `node-fetch` in the latest Strapi version (v4.6.2).

**To Reproduce**

1. Install the plugin using the latest strapi version (>= v4.6.2)

**Expected behavior**
Application should start with no error.

**Screenshots**

**Additional context**
Strapi v4.6.2 release info: https://github.com/strapi/strapi/releases/tag/v4.6.2
PR deciding to replace `request` with `node-fetch`: https://github.com/strapi/strapi/pull/15765

**Comment by apollocoder** [comment]
I can confirm this as well. If you do not want to wait for the fix, install `request` as a peer dependency:

```
npm i request
```

This is a workaround, either the plugin should change to `node-fetch` as well or include `request` on their own.

**Comment by octohuguesdumont** [comment]
Hello, we found the same problem with strapi 4.7.1

**Comment by krisdahl** [comment]
I used 
`yarn add request`
in the root strapi folder as a workaround.

**Comment by molul** [comment]
Thanks for the workaround. I couldn't update since 4.6.2 and now I've been able to update to 4.8.2 :)

**Comment by josephpage** [comment]
Hi all, I've opened PR #98 to replace the obsolete `request` module with `node-fetch` (and declaring it in `dependencies` to avoid future problems), and I'm waiting for review from the maintainer @Baboo7.

**Comment by dmurphy779** [comment]
> Hi all, I've opened PR #98 to replace the obsolete `request` module with `node-fetch` (and declaring it in `dependencies` to avoid future problems), and I'm waiting for review from the maintainer @Baboo7.

Bump - waiting on a solution before I re-install.

**Comment by Baboo7** [comment]
Thank you @josephpage. Just published version `1.18.1` with the fix
