### ISSUE TITLE
[BUG] Whole Database export does not fetch plugin content types

### ISSUE THREAD

**Issue by Kyle772** [Baboo7/strapi-plugin-import-export-entries#99]
**Describe the bug**
When running a whole db export on the plugin homepage it successfully grabs anything that is in strapi but not any plugin built content-types. 

**To Reproduce**
1) Create a content-type inside of a plugin
2) Populate some entries
3) Export whole database
4) Look through the json export
5) See there is no content types from the plugin

**Expected behavior**
Export all single and collections types from content-api AND plugin-api

**Additional context**
It looks like it's grabbing the image upload plugin's entries but there must be some logic missing to look for content types that exist within other plugins. (Maybe something is hardcoded?)

**Comment by Baboo7** [comment]
@Kyle772 checkout version `v1.19.2`, you will be able opt-in to export plugins content types when exporting the whole database

**Comment by Baboo7** [comment]
I'm considering this issue as fixed
